// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMxnmhzMxEsNJOwrjBr-P9HM1BZ_60eeE',
    appId: '1:522650697503:web:1fe3031e3dc5eb1e80ba2a',
    messagingSenderId: '522650697503',
    projectId: 'chity-chat-db-app',
    authDomain: 'chity-chat-db-app.firebaseapp.com',
    storageBucket: 'chity-chat-db-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBulkYJG3tv8O5XHKwM2KNzveo5TAkwZbQ',
    appId: '1:522650697503:android:791f54fafd22ff8980ba2a',
    messagingSenderId: '522650697503',
    projectId: 'chity-chat-db-app',
    storageBucket: 'chity-chat-db-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARLUAcM8ddp_7ckeR7NplZZcWH26gJUJA',
    appId: '1:522650697503:ios:3c0acbd3153f3f5c80ba2a',
    messagingSenderId: '522650697503',
    projectId: 'chity-chat-db-app',
    storageBucket: 'chity-chat-db-app.appspot.com',
    iosBundleId: 'com.example.chity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARLUAcM8ddp_7ckeR7NplZZcWH26gJUJA',
    appId: '1:522650697503:ios:3c0acbd3153f3f5c80ba2a',
    messagingSenderId: '522650697503',
    projectId: 'chity-chat-db-app',
    storageBucket: 'chity-chat-db-app.appspot.com',
    iosBundleId: 'com.example.chity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMxnmhzMxEsNJOwrjBr-P9HM1BZ_60eeE',
    appId: '1:522650697503:web:79f1d2e38285950280ba2a',
    messagingSenderId: '522650697503',
    projectId: 'chity-chat-db-app',
    authDomain: 'chity-chat-db-app.firebaseapp.com',
    storageBucket: 'chity-chat-db-app.appspot.com',
  );
}
